$replacements = @{
    "AHG AGRONEGOCIOS LTDA" = "AGRO EMPRESA FANTASIA LTDA"
    "AGROMIX PET CENTER LTDA" = "PET SHOP FANTASIA LTDA"
    "GLOBAL MANUTENCOES E CONSTRUCOES LTDA" = "CONSTRUTORA FANTASIA LTDA"
    "LE BRUT INDUSTRIA E COMERCIO DE ROUPAS LTDA" = "INDUSTRIA DE ROUPAS FANTASIA LTDA"
    "AHFV PARTICIPACOES LTDA" = "HOLDING FANTASIA LTDA"
    "AHFV PARTICIPAÇÕES LTDA" = "HOLDING FANTASIA LTDA"
    "ABREU PATRIMONIAL LTDA" = "PATRIMONIAL FANTASIA LTDA"
    "AMBTECH ENGENHARIA LTDA" = "ENGENHARIA FANTASIA LTDA"
    "DCS CONSTRUTORA LTDA" = "CONSTRUTORA EXEMPLO LTDA"
    "FT COMERCIO DE COMBUSTIVEIS E DERIVADOS LTDA" = "POSTO DE GASOLINA FANTASIA LTDA"
    "A A GUIMARAES A NETO EIRELI" = "EMPRESA EXEMPLO ALPHA EIRELI"
    "A. A. GUIMARAES A. NETO LTDA" = "EMPRESA EXEMPLO ALPHA EIRELI"
    "A PORTEIRA PATRIMONIAL LTDA" = "EMPRESA EXEMPLO BETA LTDA"
    "ACCIOLY LINS SERVICOS MEDICOS LTDA" = "CLINICA EXEMPLO GAMA LTDA"
    "ABO SERVICOS MEDICOS LTDA" = "CLINICA EXEMPLO DELTA LTDA"
    "MARTA.SOUZA" = "ANALISTA.FISCAL1"
    "ROBERTO" = "GERENTE.FISCAL"
    "ERIKA.CUNHA" = "ANALISTA.FISCAL2"
    "JULIA.DOTTA" = "ANALISTA.FISCAL3"
    "KESIA.CATUGY" = "ANALISTA.FISCAL4"
    "RAFAELA.JESUS" = "ANALISTA.FISCAL5"
    "MARIA.ANACISA" = "ANALISTA.FISCAL6"
    "SIMONE" = "COORDENADOR.DP"
    "INGRIDE" = "ANALISTA.CONTABIL1"
}

$files = Get-ChildItem -Path "c:\Users\DMF-AUTOMACAO\Documents\PROJETOS\N8N automacao\ESTRUTURA" -Recurse -Include *.py,*.md

foreach ($file in $files) {
    $content = Get-Content $file.FullName -Raw
    $modified = $false
    
    foreach ($key in $replacements.Keys) {
        if ($content -match [regex]::Escape($key)) {
            $content = $content -replace [regex]::Escape($key), $replacements[$key]
            $modified = $true
        }
    }
    
    if ($modified) {
        Set-Content -Path $file.FullName -Value $content -NoNewline
        Write-Host "Modified: $($file.Name)"
    }
}
